# Generated by Django 4.1.1 on 2022-11-22 15:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('creator_name', models.CharField(default='Official HungryMe', max_length=50)),
                ('number_of_ingredients', models.IntegerField(default=1)),
                ('energy_kcal', models.IntegerField(default=0.0, null=True)),
                ('fat_kcal', models.IntegerField(default=0.0, null=True)),
                ('sugar', models.IntegerField(default=0.0, null=True)),
                ('picture_url', models.URLField(default='', null=True)),
                ('rating', models.FloatField(default=0.0, null=True)),
                ('difficulty', models.CharField(default='None', max_length=30, null=True)),
                ('description', models.CharField(default='No description', max_length=250, null=True)),
                ('ingredients', models.JSONField(default=None, null=True)),
                ('nutrition', models.JSONField(default=None, null=True)),
                ('category', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foods.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_date', models.DateTimeField(default=datetime.datetime(2022, 11, 23, 15, 48, 48, 76059, tzinfo=datetime.timezone.utc), verbose_name='date end')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foods.menu')),
            ],
        ),
        migrations.CreateModel(
            name='CookBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('cook_name', models.CharField(max_length=200)),
                ('description', models.CharField(default='No description', max_length=250, null=True)),
                ('ingredients', models.JSONField(default=None, null=True)),
                ('picture_url', models.URLField(default='', null=True)),
                ('number_of_ingredients', models.IntegerField(default=1)),
                ('energy_kcal', models.FloatField(default=0.0, null=True)),
                ('fat_kcal', models.FloatField(default=0.0, null=True)),
                ('sugar', models.FloatField(default=0.0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('room_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.menu')),
            ],
        ),
    ]
