# Generated by Django 4.1.1 on 2022-11-22 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodofday',
            name='range_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 15, 57, 9, 954037, tzinfo=datetime.timezone.utc), verbose_name='date end'),
        ),
    ]
