# Generated by Django 3.2.7 on 2022-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20221021_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(default='No description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='difficulty',
            field=models.CharField(default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='kcal',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='picture_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='total_cooking_time',
            field=models.CharField(default='15 minutes', max_length=25, null=True),
        ),
    ]
