# Generated by Django 3.2.7 on 2022-10-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20221024_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
