# Generated by Django 4.1.1 on 2022-11-29 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_alter_foodofday_range_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookbook",
            name="rating",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="foodofday",
            name="range_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 30, 19, 38, 25, 812290, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date end",
            ),
        ),
    ]
