# Generated by Django 3.2.7 on 2022-10-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_menu_nutrition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='kcal',
            new_name='energy_kcal',
        ),
    ]
