# Generated by Django 3.2.7 on 2022-10-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_rename_kcal_menu_energy_kcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nutrition',
            field=models.JSONField(default=None, null=True),
        ),
    ]
