# Generated by Django 3.2.7 on 2022-10-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_auto_20221025_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='fat_kcal',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='sugar',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
