# Generated by Django 4.1.1 on 2022-10-31 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0009_remove_menu_nutrition"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodOfDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            11,
                            1,
                            10,
                            21,
                            31,
                            835600,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="date end",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="foods.menu"
                    ),
                ),
            ],
        ),
    ]
