# Generated by Django 3.2.14 on 2022-10-29 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_remove_menu_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='range_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 21, 4, 18, 941112, tzinfo=utc), verbose_name='date end'),
        ),
    ]
