# Generated by Django 3.2.14 on 2022-10-29 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_menu_range_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='range_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 21, 11, 48, 166468, tzinfo=utc), verbose_name='date end'),
        ),
    ]
