# Generated by Django 3.2.14 on 2022-10-30 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_alter_menu_range_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_date', models.DateTimeField(default=datetime.datetime(2022, 10, 31, 6, 48, 54, 292937, tzinfo=utc), verbose_name='date end')),
                ('menu_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='range_date',
        ),
    ]
