# Generated by Django 4.1.1 on 2022-11-06 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0020_menu_total_cooking_time_alter_foodofday_range_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="total_cooking_time",),
        migrations.AlterField(
            model_name="foodofday",
            name="range_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 7, 12, 29, 21, 231752, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date end",
            ),
        ),
    ]
