# Generated by Django 4.1.1 on 2022-11-07 17:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("foods", "0021_remove_menu_total_cooking_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodofday",
            name="range_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 8, 17, 3, 41, 234773, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date end",
            ),
        ),
        migrations.CreateModel(
            name="CookBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("cook_name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(
                        default="No description", max_length=250, null=True
                    ),
                ),
                ("ingredients", models.JSONField(default=None, null=True)),
                ("picture_url", models.URLField(default="", null=True)),
                ("number_of_ingredients", models.IntegerField(default=1)),
                ("energy_kcal", models.FloatField(default=0.0, null=True)),
                ("fat_kcal", models.FloatField(default=0.0, null=True)),
                ("sugar", models.FloatField(default=0.0, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
