# Generated by Django 4.1.1 on 2022-11-12 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0024_alter_foodofday_range_date_reply_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="category",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="nutrition",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="foodofday",
            name="range_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 13, 15, 58, 8, 467393, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date end",
            ),
        ),
    ]
