# Generated by Django 4.1.1 on 2022-11-13 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0025_menu_category_menu_nutrition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodofday",
            name="range_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 14, 15, 16, 40, 792819, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date end",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="energy_kcal",
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="fat_kcal",
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="sugar",
            field=models.IntegerField(default=0.0, null=True),
        ),
    ]
