# Generated by Django 4.1.1 on 2022-11-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0025_menu_category_menu_nutrition_and_more"),
        ("foods", "0033_alter_foodofday_range_date"),
    ]

    operations = []
