# Generated by Django 4.1.1 on 2022-11-15 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0036_alter_foodofday_range_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="menu",),
        migrations.RemoveField(model_name="comment", name="review",),
        migrations.AddField(
            model_name="comment",
            name="room_name",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="foods.menu"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment", name="user", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="foodofday",
            name="range_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 16, 15, 31, 32, 160498, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date end",
            ),
        ),
        migrations.DeleteModel(name="Reply",),
    ]
