# Generated by Django 4.1.1 on 2022-11-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0026_alter_foodofday_range_date_alter_menu_energy_kcal_and_more"),
        ("foods", "0037_remove_comment_menu_remove_comment_review_and_more"),
    ]

    operations = []
