# Generated by Django 4.1.1 on 2022-11-19 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0038_merge_20221119_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodofday',
            name='range_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 21, 8, 52, 24574, tzinfo=datetime.timezone.utc), verbose_name='date end'),
        ),
    ]
