# Generated by Django 4.1.1 on 2022-11-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0038_merge_20221119_2032"),
        ("foods", "0039_alter_foodofday_range_date"),
    ]

    operations = []
