# Generated by Django 4.1.1 on 2022-11-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0040_merge_20221122_1216"),
        ("foods", "0042_alter_foodofday_range_date"),
    ]

    operations = []
