# Generated by Django 4.1.1 on 2022-11-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0043_merge_20221123_0257"),
        ("foods", "0045_alter_foodofday_range_date"),
    ]

    operations = []
